Add clang21 support + remove clang17 (#331)
This PR removes clang 17 builds and adds clang 21 builds.

Changes required for clang 21:
- Remove -c when running preprocessor. Clang 21 now emits a warning for
unnecessary -c:
```
clang: error: argument unused during compilation: '-c' [-Wunused-command-line-argument]
```
- Bump cassandra-cpp-driver to 2.9.0-yb-16 to address the following
error:
```
[cassandra-cpp-driver (clang21, uninstrumented)] src/cassandra-cpp-driver-2.9.0-yb-15/src/md5.cpp:151:10: error: first argument in call to 'memset' is a pointer to non-trivially copyable type 'cass::Md5' [-Werror,-Wnontrivial-memcall]
[cassandra-cpp-driver (clang21, uninstrumented)]   151 |   memset(this, 0, sizeof(Md5));
[cassandra-cpp-driver (clang21, uninstrumented)]       |          ^
[cassandra-cpp-driver (clang21, uninstrumented)] src/cassandra-cpp-driver-2.9.0-yb-15/src/md5.cpp:151:10: note: explicitly cast the pointer to silence this warning
[cassandra-cpp-driver (clang21, uninstrumented)]   151 |   memset(this, 0, sizeof(Md5));
[cassandra-cpp-driver (clang21, uninstrumented)]       |          ^
[cassandra-cpp-driver (clang21, uninstrumented)]       |          (void*)
[cassandra-cpp-driver (clang21, uninstrumented)] 1 error generated.
```

Also bump llvm-installer to 1.4.12 (BOLT binaries for llvm21 builds).