Get the Linuxbrew directory from the env variable YB_LINUXBREW_DIR. (#18)
On CentOS the code was not compiling due to the Linuxbrew dir not being
properly used. This change corrects that.

Example stack trace of the error being fixed:
```
Traceback (most recent call last):
  File "/repositories/yugabyte-db4/thirdparty/yb_build_thirdparty_main.py", line 935, in <module>
    main()
  File "/repositories/yugabyte-db4/thirdparty/yb_build_thirdparty_main.py", line 929, in main
    builder = Builder()
  File "/repositories/yugabyte-db4/thirdparty/yb_build_thirdparty_main.py", line 144, in __init__
    self.detect_linuxbrew()
  File "/repositories/yugabyte-db4/thirdparty/yb_build_thirdparty_main.py", line 321, in detect_linuxbrew
    self.linuxbrew_dir = get_linuxbrew_dir()
NameError: name 'get_linuxbrew_dir' is not defined
CMake Error at CMakeLists.txt:564 (message):
  Thirdparty was built unsuccessfully, terminating.
```